### ISSUE TITLE
Nowcasting vs forecasting

### ISSUE THREAD

**Issue by AZFARHAD24511** [viczommers/MIDAS-Nowcast#1]
I believe there might be a slight misunderstanding regarding Nowcasting. It appears that you utilized monthly data to predict seasonal variables. However, it's important to note that this approach doesn't align with the essence of Nowcasting. Nowcasting involves predicting the target variable on a monthly basis, aiming for real-time or near-real-time forecasts. It's a faster process than what was expected. I kindly suggest delving into articles specifically addressing the concept of Nowcasting to gain a clearer understanding of its methodology and objectives.

**Comment by viczommers** [comment]
Thank you. In statistical production, nowcasting can refer to any prediction (e.g. First Estimate) before the first official release. Given that Quarterly variables in the UK are published with 1-Qtr lag, it is considered acceptable inside the statistical agencies to use all 3 monthly observations (within Quarter $\hat{Y_q}$) and output a single prediction. This still gives data users a practical 1-to-2 months lead before the first release becomes available; there are no parametric requirements for $\hat{Y}$ horizons to match frequency of predictors. Nowcasting therefore can also refer to the prediction of near-past.

Bank's nowcast is published Quarterly (Feb, May, Aug, Nov), but without a lag. 
![Table_Lags](https://github.com/viczommers/MIDAS-Nowcast/assets/149804703/255ca381-7e84-4d5c-87d5-2304467aa02b)
